// labs/K33402/Тюмин Никита/lab3/src/components/HeaderComponent.vue
<template>
  <nav class="navbar navbar-expand-lg sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" @click="$router.push({name: 'home'})" style="color: var(--header-color);cursor:pointer">Musec</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <input
        v-on:keyup.enter="goToSearchPage"
        v-model="search"
        class="form-control me-2"
        type="search"
        placeholder="Search"
        aria-label="Search"
      >

      <div class="collapse navbar-collapse" id="navbarScroll">

        <ul class="navbar-nav ms-auto d-flex flex-row">
          <li class="nav-item dropdown">

            <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp" class="rounded-circle" height="25" alt="Black and White Portrait of a Man" loading="lazy" />
            </a>

            <ul class="dropdown-menu dropdown-menu-end" style="background-color: var(--header-color);">
              <li><a class="dropdown-item" @click="$router.push({name: 'profile'})">Profile</a></li>
              <li><a class="dropdown-item" href="#" @click.prevent="logout">Logout</a></li>
            </ul>

          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
import {mapStores} from "pinia";
import useAuthStore from "../pinia/auth";

export default {
  data: () => ({
    search: '',
  }),
  computed: {
    ...mapStores(useAuthStore)
  },
  methods: {
    goToSearchPage() {
      this.$router.push({ name: 'search', query: {q: this.search} })
    },
    logout() {
      this.authStore.logout()
    },
  }
}
</script>

<style scoped>

</style>

// labs/K33402/Жаров Александр/lab1/portfolio/frontend/src/components/Header/Header.jsx
import "./Header.css";
import React from "react";
import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/esm/Button";
import icon from "../../img/main-icon.svg";
import { Link } from "react-router-dom";

function Header() {
  return (
    <>
      <Navbar expand="md" className="body" data-bs-theme="dark" sticky="top">
        <Container>
          <Navbar.Brand>
            <img
              src={icon}
              className="d-inline-block align-top"
              alt="React Bootstrap logo"
            />
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />

          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="me-auto item-container">
              <Link to="/" className="link">
                Профиль
              </Link>
              <Link to="account" className="link">
                Личный кабинет
              </Link>
            </Nav>
            <Form className="md-block">
              <Form.Control
                type="search"
                placeholder="Search"
                className="me-2"
                aria-label="Search"
              />
              <Button variant="outline-success">Search</Button>
            </Form>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    </>
  );
}

export default Header;
