// labs/K33402/Рашевский Вячеслав/lab3/src/components/SignInComponent.vue
<script setup>
import {signinUser} from "@/auth_script";
import router from "@/router";

async function signIn() {
  const ans = await signinUser();
  if (!ans) {
    await router.push('/auth');
  } else {
    await router.push('/account');
  }
}
</script>

<template>
  <form id="signinForm" class="card col-5 my-3 mx-3 card-body">
    <h5 class="card-title text-center">Sign in</h5>
    <label class="form-label" for="email-in">Email:</label>
    <input type="text" name="login" id="email-in" placeholder="Email..." class="form-control mb-1">
    <label class="form-label" for="password-in">Password:</label>
    <input type="password" name="password" id="password-in" placeholder="Password..." class="form-control mb-1">
    <router-link @click="signIn" type="submit" class="btn btn-primary form-control my-1" to="">Sign in
    </router-link>
  </form>
</template>

<style scoped>

</style>

// labs/K33392/Рыбалко_Олег/lab1/src/layouts/SignIn/index.tsx
import { useTranslation } from 'react-i18next'
import styles from './SignIn.module.scss'

export function SignInLayout() {
  const { t } = useTranslation('signin')
  const { t: tGlobal } = useTranslation('global')

  return (
    <div
      className={`container d-flex justify-content-center align-items-center ${styles.signinContainer}`}
    >
      <form className={styles.signinForm}>
        <h1 className="h1 mb-3">{tGlobal('title')}</h1>
        <h1 className="h3 mb-3 fw-normal">{t('signinToAccount')}</h1>

        <div className="form-floating">
          <input
            type="email"
            className={`form-control ${styles.formEmail}`}
            id="floatingInput"
            placeholder="name@example.com"
          />
          <label htmlFor="floatingInput">{t('emailLabel')}</label>
        </div>
        <div className="form-floating">
          <input
            type="password"
            className={`form-control ${styles.formPassword}`}
            id="floatingPassword"
            placeholder="Password"
          />
          <label htmlFor="floatingPassword">{t('passwordLabel')}</label>
        </div>
        <button className="w-100 btn btn-lg btn-primary" type="submit">
          {t('signinButton')}
        </button>
      </form>
    </div>
  )
}
